config = {
    "mode": "train",
    "last_state": None,
    "best_model": "/kaggle/working/checkpoint/best.ckpt",
    "cp_path": "/kaggle/working/checkpoint",
    "select_concept_data_path": "/kaggle/input/datasets/tmtrnhelloworld/klselectconceptadaalgo/select_concept_data.pth",
    "dataset_name": "cub",
    "dataset_dir": "/kaggle/input/datasets/tmtrnhelloworld/cub2002011splitted",
    "monitor": "val_y_bmac",
    "start_epoch": 1,
    "end_epoch": 1,
    "optimizer": {"optimizer": "adamw", "lr": 0.0001},
    "amp": True,
    "batch_size": 64,
    "transform": "uniform",
    "loss": {
        "cpt_lambda": 1,
        "cls_lambda": 1,
        "cy_lambda": 1,
    },
    "model": {
        "backbone": "resnet101",
        "emb_size": 2048,
        "hid_size": 512,
        "cpt_size": 312,
        "cy_perturb_prob": 0.2,
        "cy_permute_prob": 0.2,
    },
}
